### PR TITLE
Added support to net20 through Theraot.Core

### PR DESCRIPTION
**Pull request by Hazzard17h**
Updated project to multi-target frameworks.

### CODE REVIEW

**Comment by mikeobrien** [comment]
Having trouble opening the project with VS 2017. I rolled it back for now. If you can test it under 2017 and make sure it works I can get it merged. Thx for the contrib tho!

**Comment by Hazzard17h** [comment]
I developed it on VS 2017 community! What trouble do you have?
To build make sure to clean obj folder. I noticed that VS clean may not work properly, eventually do it by hand.

**Comment by mikeobrien** [comment]
Here is the build log: [Hid_Library_Deploy_3.2.47.0.log](https://github.com/mikeobrien/HidLibrary/files/1746080/Hid_Library_Deploy_3.2.47.0.log)

**Comment by Hazzard17h** [comment]
Please see #97

**Pull request merged**
