### PR TITLE
Expose GetInputReport and SetOutputReport through native interface

### PR DESCRIPTION
**Pull request by bprescott**
I needed access to a couple of the native methods hidden in the NativeMethods private class so I exposed them in the HidDevice class

### CODE REVIEW

**Comment by amullins83** [comment]
Why do you feel like you need to access the reports directly instead of using the `Read` and `Write` methods already available?

**Comment by bprescott** [comment]
The way my code is structured I wanted to read the passive cached report that contains device config info.  he SetOutputReport is for symmetry.   Do you see a problem with exposing these interfaces at the device level.  I did not see a conflict, but I have not studied the code in enough detail to see if there are side effects of exposing these interfaces.

**Comment by amullins83** [comment]
It's not a question of whether there are side effects. It's just a matter of why. The device model provides a layer of abstraction over the native method calls, with a particular pattern in the form of methods beginning with the words `Read` and `Write`. I don't understand why you would want to break that abstraction here.

If it's a matter of using caching to optimize reading, maybe there could be a `ReadCached` method or something similar that follows the pattern of the existing `Read` methods.

**Comment by bprescott** [comment]
Ok, I see what you are getting at and it makes sense.  Let me refactor and weave the native calls into the existing abstraction you have defined.

**Comment by mikeobrien** [comment]
Ok, build server back up and running, just deployed to the nuget gallery. Deploy normally happens automatically once its merged so should be good from here on out. Sorry for the delay!

**Comment by bprescott** [comment]
Thanks Mike, we will pick up the released build in our next round.  Many
thanks!


Bill Prescott
Director SW Engineering
Logitech Inc.
ph: 510.713.4946
gv: 510.545.3878
@: bill_prescott@logitech.com

**Comment by mikeobrien** [comment]
No problem!

**Pull request merged**
