### PR TITLE
Target Net Standard 2.0

### PR DESCRIPTION
**Pull request by w-michal**
Few minor changes inside csproj:

- Added netstandard2 target.
- Moved nuspec metadata into csproj (Msbuild can now create nupkg directly with /t:pack).
- Removed unused references.
- Updated test csproj.

Also updated gulp file to support restoring packages and switched to msbuild for package build.

PS - Looks like your build agent is not up to date (does not have the latest MsBuild installed?)

### CODE REVIEW

**Comment by amullins83** [comment]
Can you check on the build agent issue? @mikeobrien might need to look at it.

**Comment by mikeobrien** [comment]
@amullins83 looking into this, I'll try to get it fixed today or tomorrow.

**Comment by mikeobrien** [comment]
Hey @amullins83 I'm migrating the build for this over to Azure Dev Ops to make it easier for others to manage it. I just added you to the HID Library team, not sure if it notifies you. Lemme know if you don't see anything. I'll make you and admin on the project as well. Anyways, hopefully this will kill two birds with one stone.

**Comment by amullins83** [comment]
Thanks. I got a notification that the name changed and I was a bit confused
because I didn't know I was on that AzDO team. The company I work for uses
AzDO, so I'm familiar with that system, though not as much on the NuGet
part.

Austin Mullins

**Comment by mikeobrien** [comment]
Cool, well I'll try to get it wrapped up tomorrow. My company is using it too, not hard to use. Nice thing is you can set it to use the latest version of windows so the tooling never gets behind like it is now on my personal server.

**Comment by mikeobrien** [comment]
@amullins83 so the Azure build is setup and working. Commits to master will push the nuget, branches and PR's will trigger builds but not push the nuget (just package it). It's configured to use the latest build tools so hopefully we dont have to worry about falling behind. Added you as an admin so you can get in there too. Let me know if we need anything else done with the build stuff.

Oh, and I haven't tested PR builds. AFAIK it *should* work and it should show a build result banner. I dont have time ATM to test that but let me know if you notice that not working.

**Comment by mikeobrien** [comment]
@w-michal BTW, the node build is no more but I added package restore to the azure build so that part is covered. Thx for working on this and sorry for the slow response.

**Comment by mikeobrien** [comment]
Oh and one last message (like Frog and Toad said):

- Azure build file is here: https://github.com/mikeobrien/HidLibrary/blob/master/azure-pipelines.yml
- Azure build pipeline is here: https://dev.azure.com/hcoverlambda/HIDLibrary/_build

**Comment by w-michal** [comment]
@mikeobrien removed changes to node build, so I think this PR is good to go.

**Comment by mikeobrien** [comment]
@w-michal ok cool, just merged, thx!

**Pull request merged**
